<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/BranchesDbReference" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://TargetNamespace.com/HCMLocationsRestRef_Operation1_response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/HCMCloudServices/HCMLocations/HCMLocationsRestRef"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMLocations/BranchesDbReference"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/HCMLocationsRestRef.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/HCMLocationsRestRef_Operation1_response"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BranchesDbReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="HcmAdmBranchesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BranchesDbReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE MAR 06 15:46:13 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:HcmAdmBranchesCollection>
         <xsl:for-each select="/ns0:Root-Element/ns0:items">
            <tns:HcmAdmBranches>
               <tns:code>
                  <xsl:value-of select="ns0:LocationCode"/>
               </tns:code>
               <tns:aDesc>
                  <xsl:value-of select="ns0:LocationName"/>
               </tns:aDesc>
               <tns:brchType>
                  <xsl:value-of select="ns0:LocationDFF/ns0:locationvlaue"/>
               </tns:brchType>
               <tns:sothCode>
                  <xsl:value-of select="ns0:LocationDFF/ns0:location"/>
               </tns:sothCode>
               <tns:status>1</tns:status>
               <tns:dateModified/>
               <tns:openingDate>
                  <xsl:value-of select="ns0:CreationDate"/>
               </tns:openingDate>
               <tns:dateUpd>
                  <xsl:value-of select="ns0:LastUpdateDate"/>
               </tns:dateUpd>
               <tns:branchSizeDesc>
                  <xsl:value-of select="ns0:LocationDFF/ns0:locationvlaue_Display"/>
               </tns:branchSizeDesc>
               <tns:brchLocCode>
                  <xsl:value-of select="ns0:LocationId"/>
               </tns:brchLocCode>
               <tns:brchLocDesc>
                  <xsl:value-of select="ns0:LocationDFF/ns0:location_Display"/>
               </tns:brchLocDesc>
            </tns:HcmAdmBranches>
         </xsl:for-each>
      </tns:HcmAdmBranchesCollection>
   </xsl:template>
</xsl:stylesheet>
