<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbQueryGetFileStructure" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://www.fact.com.jo" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SalaryBulk/GetFileStructure/dbQueryGetFileStructure"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/SalaryBulk/GetFileStructure/GetFileStructure">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbQueryGetFileStructure.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbQueryGetFileStructure"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GetFileStructure.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Output" namespace="http://www.fact.com.jo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [THU MAR 22 14:58:03 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Output>
         <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORD">
            <tns:GetData>
               <tns:CMPN_CODE>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CMPN_CODE"/>
               </tns:CMPN_CODE>
               <tns:CFVR_CODE>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CFVR_CODE"/>
               </tns:CFVR_CODE>
               <tns:CFDT_LINE_TYPE>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CFDT_LINE_TYPE"/>
               </tns:CFDT_LINE_TYPE>
               <tns:CFDT_POS>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CFDT_POS"/>
               </tns:CFDT_POS>
               <tns:CFDT_LEN>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CFDT_LEN"/>
               </tns:CFDT_LEN>
               <tns:CFDT_VAL>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:CFDT_VAL"/>
               </tns:CFDT_VAL>
               <tns:NODE_ID>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:NODE_ID"/>
               </tns:NODE_ID>
               <tns:PROGRAM_ID>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:PROGRAM_ID"/>
               </tns:PROGRAM_ID>
               <tns:USER_ID>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:USER_ID"/>
               </tns:USER_ID>
               <tns:TIME_STAMP>
                  <xsl:value-of select="ns0:P_RECORD_Row/ns0:TIME_STAMP"/>
               </tns:TIME_STAMP>
            </tns:GetData>
         </xsl:for-each>
      </tns:Output>
   </xsl:template>
</xsl:stylesheet>
