<wsdl:definitions
     name="TransferdbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMTransfersPromotions/TransferdbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMTransfersPromotions/TransferdbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/TransferdbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="TransferdbReference_plt" >
    <plt:role name="TransferdbReference_role" >
      <plt:portType name="tns:TransferdbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/TransferdbReference" schemaLocation="../Schemas/TransferdbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="HcmEmpTransferMCollection_msg">
        <wsdl:part name="HcmEmpTransferMCollection" element="top:HcmEmpTransferMCollection"/>
    </wsdl:message>
    <wsdl:portType name="TransferdbReference_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:HcmEmpTransferMCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
