<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ResignationRestRef"
     targetNamespace="http://xmlns.oracle.com/HCMCloudServices/HCMResignationActionOneWay/ResignationRestRef"
     xmlns:tns="http://xmlns.oracle.com/HCMCloudServices/HCMResignationActionOneWay/ResignationRestRef"
     xmlns:inp1="http://xmlns.oracle.com/HCMCloudServices/HCMResignationActionOneWay/ResignationRestRef"
     xmlns:inp2="http://TargetNamespace.com/ResignationRestRef_getAllEmps_response"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ResignationRestRef">
        <plnk:role name="ResignationRestRefProvider" portType="tns:ResignationRestRef_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.oracle.com/HCMCloudServices/HCMResignationActionOneWay/ResignationRestRef"
             elementFormDefault="qualified">
            <element name="empty">
                <complexType/>
            </element>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/ResignationRestRef_getAllEmps_response"
                 schemaLocation="../Schemas/nxsd_schema1.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Rest_EmptyMessage">
        <wsdl:part name="Empty" element="tns:empty"/>
    </wsdl:message>
    <wsdl:message name="getAllEmps_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="ResignationRestRef_ptt">
        <wsdl:operation name="getAllEmps">
            <wsdl:input message="tns:Rest_EmptyMessage"/>
            <wsdl:output message="tns:getAllEmps_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
