<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="submitReverseTransactionReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SAMAHA/SubmitReverseTransaction/submitReverseTransactionReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SAMAHA/SubmitReverseTransaction/submitReverseTransactionReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/submitReverseTransactionReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.example.org"
    >
    <plt:partnerLinkType name="submitReverseTransactionReference_plt">
        <plt:role name="submitReverseTransactionReference_role">
            <plt:portType name="tns:submitReverseTransactionReference_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SAMAHA/SubmitReverseTransaction/submitReverseTransactionReference"
             xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/submitReverseTransactionReference"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.example.org">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/submitReverseTransactionReference"
                 schemaLocation="../Schemas/submitReverseTransactionReference_sp.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SAMAHA/SubmitReverseTransaction/submitReverseTransactionReference"
             xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/submitReverseTransactionReference"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.example.org">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/submitReverseTransaction.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="submitReverseTransactionReference_ptt">
        <wsdl:operation name="submitReverseTransactionReference">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
