<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://employee.fact" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmpPaySlipReference" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HR/EmployeeService/getEmpPaySlipReference"
                xmlns:ax211="http://employeeFinancial.bean.fact/xsd"
                xmlns:ax230="http://WorkFlowStructure.bean.fact/xsd"
                xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:ns2="http://org.apache.axis2/xsd"
                xmlns:ax28="http://evaluation.bean.fact/xsd" xmlns:ax214="http://employeeInfoDetails.bean.fact/xsd"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ax227="http://salarySlip.bean.fact/xsd"
                xmlns:ax217="http://leave.bean.fact/xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ax224="http://employment.bean.fact/xsd"
                xmlns:ax238="http://dao.fact/xsd" xmlns:ax233="http://utility.bean.fact/xsd"
                xmlns:ax225="http://common.bean.fact/xsd" xmlns:ax221="http://employee.bean.fact/xsd"
                xmlns:ax21="http://vacation.bean.fact/xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ax236="http://email.bean.fact/xsd" xmlns:ax25="http://overTime.bean.fact/xsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/getEmpPaySlipReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmpPaySlipReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EmployeeService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getEmpPayslipResponse" namespace="http://employee.fact"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU DEC 06 05:45:49 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
       <tns:getEmpPayslipResponse>
         <tns:return>
            <ax225:webServiceResponseMessage/>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:EMP_NAME_A )">
               <ax227:arabicName>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:EMP_NAME_A"/>
               </ax227:arabicName>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY )">
               <ax227:basicSalary>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY"/>
               </ax227:basicSalary>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY_CODE )">
               <ax227:basicSalaryCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY_CODE"/>
               </ax227:basicSalaryCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BRCH )">
               <ax227:branch>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BRCH"/>
               </ax227:branch>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:COMPUTER_ALW )">
               <ax227:computerAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:COMPUTER_ALW"/>
               </ax227:computerAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:COMPUTER_ALW_CODE )">
               <ax227:computerAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:COMPUTER_ALW_CODE"/>
               </ax227:computerAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:EMP_ACNT_NO )">
               <ax227:empAccountNumber>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:EMP_ACNT_NO"/>
               </ax227:empAccountNumber>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY_EXTRA )">
               <ax227:extraBasicSalary>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:BASIC_SALARY_EXTRA"/>
               </ax227:extraBasicSalary>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SALARY_EXTRA_CODE )">
               <ax227:extraBasicSalaryCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SALARY_EXTRA_CODE"/>
               </ax227:extraBasicSalaryCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW_EXTRA )">
               <ax227:extraFamilyAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW_EXTRA"/>
               </ax227:extraFamilyAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAM_ALW_EXT_CODE )">
               <ax227:extraFamilyAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAM_ALW_EXT_CODE "/>
               </ax227:extraFamilyAllowanceCode>
            </xsl:if>
            <ax227:familyAllowance>
               <ax227:key/>
               <ax227:value/>
            </ax227:familyAllowance>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:GRADE )">
               <ax227:grade>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:GRADE"/>
               </ax227:grade>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MANAGENT_ALW )">
               <ax227:managementAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MANAGENT_ALW"/>
               </ax227:managementAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MANAGENT_ALW_CODE )">
               <ax227:managementAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MANAGENT_ALW_CODE"/>
               </ax227:managementAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:NET_SALARY )">
               <ax227:netSalary>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:NET_SALARY"/>
               </ax227:netSalary>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:NET_SALARY_CODE )">
               <ax227:netSalaryCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:NET_SALARY_CODE"/>
               </ax227:netSalaryCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TA )">
               <ax227:netSalaryDescription>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TA"/>
               </ax227:netSalaryDescription>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHER_DED )">
               <ax227:otherDeduction>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHER_DED"/>
               </ax227:otherDeduction>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHER_DED_CODE )">
               <ax227:otherDeductionCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHER_DED_CODE"/>
               </ax227:otherDeductionCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OVERTIME_ALW )">
               <ax227:overTimeAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OVERTIME_ALW"/>
               </ax227:overTimeAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OVERTIME_ALW_CODE )">
               <ax227:overTimeAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OVERTIME_ALW_CODE"/>
               </ax227:overTimeAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:PAY_DATE )">
               <ax227:salarySlipDate>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:PAY_DATE"/>
               </ax227:salarySlipDate>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SOCIAL_DED )">
               <ax227:socialDeduction>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SOCIAL_DED"/>
               </ax227:socialDeduction>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SOCIAL_DED_CODE )">
               <ax227:socialDeductionCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SOCIAL_DED_CODE"/>
               </ax227:socialDeductionCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SPC_ALW )">
               <ax227:specialAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SPC_ALW"/>
               </ax227:specialAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SPC_ALW_CODE )">
               <ax227:specialAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:SPC_ALW_CODE"/>
               </ax227:specialAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TAX_DED )">
               <ax227:taxDeduction>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TAX_DED"/>
               </ax227:taxDeduction>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TAX_DED_CODE )">
               <ax227:taxDeductionCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TAX_DED_CODE"/>
               </ax227:taxDeductionCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TELLER_ALW )">
               <ax227:tellerAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TELLER_ALW"/>
               </ax227:tellerAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TELLER_ALW_CODE )">
               <ax227:tellerAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TELLER_ALW_CODE"/>
               </ax227:tellerAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_ALW )">
               <ax227:totalAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_ALW"/>
               </ax227:totalAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_ALW_CODE )">
               <ax227:totalAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_ALW_CODE"/>
               </ax227:totalAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_DED )">
               <ax227:totalDeduction>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_DED"/>
               </ax227:totalDeduction>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_DED_CODE )">
               <ax227:totalDeductionCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:TOTAL_DED_CODE"/>
               </ax227:totalDeductionCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW )">
               <ax227:totalFamilyAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW"/>
               </ax227:totalFamilyAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW_CODE )">
               <ax227:totalFamilyAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:FAMILY_ALW_CODE"/>
               </ax227:totalFamilyAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MOVE_ALW )">
               <ax227:totalMoveAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MOVE_ALW"/>
               </ax227:totalMoveAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MOVE_ALW_CODE )">
               <ax227:totalMoveAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:MOVE_ALW_CODE"/>
               </ax227:totalMoveAllowanceCode>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHERS_ALW )">
               <ax227:totalOtherAllowance>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHERS_ALW"/>
               </ax227:totalOtherAllowance>
            </xsl:if>
            <xsl:if test="boolean (/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHERS_ALW_CODE )">
               <ax227:totalOtherAllowanceCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_EMP_PAYSLIP/ns0:OUT_CUR_EMP_PAYSLIP_Row/ns0:OTHERS_ALW_CODE"/>
               </ax227:totalOtherAllowanceCode>
            </xsl:if>
         </tns:return>
      </tns:getEmpPayslipResponse>
   </xsl:template>
</xsl:stylesheet>
