<wsdl:definitions
     name="StagedbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMEmpsDep/StagedbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMEmpsDep/StagedbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagedbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="StagedbReference_plt" >
    <plt:role name="StagedbReference_role" >
      <plt:portType name="tns:StagedbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagedbReference" schemaLocation="../Schemas/StagedbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="HcmEmployeeDependenciesCollection_msg">
        <wsdl:part name="HcmEmployeeDependenciesCollection" element="top:HcmEmployeeDependenciesCollection"/>
    </wsdl:message>
    <wsdl:portType name="StagedbReference_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:HcmEmployeeDependenciesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
