<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://TargetNamespace.com/HCMGradesRestRef_GetGrades_response" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertGradesDbReference" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.oracle.com/HCMCloudServices/HCMGrades/HCMGradesRestRef"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMGrades/InsertGradesDbReference"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/HCMGradesRestRef.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/HCMGradesRestRef_GetGrades_response"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/InsertGradesDbReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="HcmGradeMCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertGradesDbReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE MAR 06 16:11:11 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:HcmGradeMCollection>
         <xsl:for-each select="/ns0:Root-Element/ns0:items">
            <tns:HcmGradeM>
               <tns:code>
                  <xsl:value-of select="ns0:GradeCode"/>
               </tns:code>
               <tns:aDesc>
                  <xsl:value-of select="ns0:GradeName"/>
               </tns:aDesc>
               <tns:insDegree>
                  <xsl:value-of select="ns0:GradeCustomerFlex/ns0:insuranceDegree"/>
               </tns:insDegree>
               <tns:status>1</tns:status>
               <tns:dateCreated/>
               <tns:dateModified/>
               <tns:id>
                  <xsl:value-of select="ns0:GradeId"/>
               </tns:id>
               <tns:parentCode>
                  <xsl:value-of select="ns0:GradeCustomerFlex/ns0:parentCode"/>
               </tns:parentCode>
               <tns:childCode>
                  <xsl:value-of select="ns0:GradeCustomerFlex/ns0:childCode"/>
               </tns:childCode>
            </tns:HcmGradeM>
         </xsl:for-each>
      </tns:HcmGradeMCollection>
   </xsl:template>
</xsl:stylesheet>
