<wsdl:definitions
     name="InsertJobsDbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMJobs/InsertJobsDbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMJobs/InsertJobsDbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertJobsDbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertJobsDbReference_plt" >
    <plt:role name="InsertJobsDbReference_role" >
      <plt:portType name="tns:InsertJobsDbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertJobsDbReference" schemaLocation="../Schemas/InsertJobsDbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="HcmJobMCollection_msg">
        <wsdl:part name="HcmJobMCollection" element="top:HcmJobMCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertJobsDbReference_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:HcmJobMCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
