<wsdl:definitions
     name="dbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMEmpsProfile/dbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMEmpsProfile/dbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReference_plt" >
    <plt:role name="dbReference_role" >
      <plt:portType name="tns:dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference" schemaLocation="../Schemas/dbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="HcmEmployeeProfileCollection_msg">
        <wsdl:part name="HcmEmployeeProfileCollection" element="top:HcmEmployeeProfileCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbReference_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:HcmEmployeeProfileCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
