<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:client="http://xmlns.oracle.com/OFMInMemoryUtilities/RefreshAllDataservice/RefreshAllProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://xmlns.oracle.com/bpel/RADS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plnk client xsd ns1 wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../RefreshAllProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="input" namespace="http://xmlns.oracle.com/bpel/RADS"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../RefreshAllProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="output" namespace="http://xmlns.oracle.com/bpel/RADS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT OCT 06 13:59:20 EEST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:output>
      <ns1:MessageBody>
        <ns1:ErrorInformation>
          <xsl:choose>
            <xsl:when test="not(((/ns1:input = &quot;QUERIES_DATA&quot; or /ns1:input = &quot;COMPOSITE_DATA&quot;) or ((/ns1:input = &quot;ERROR_DATA&quot;) or ((/ns1:input = &quot;MAPPING_DATA&quot;) or ((/ns1:input = &quot;ATTRIBUTEVALIDATION_DATA&quot;) or ((/ns1:input = &quot;PARAMETER_DATA&quot;) or ((/ns1:input = &quot;VALIDATION_DATA&quot;) or ((/ns1:input = &quot;ORDER_DATA&quot;) or ((/ns1:input = &quot;SIEBELPRODUCT_DATA&quot;) or ((/ns1:input = &quot;PROFILEATTRIBUTES_DATA&quot;) or ((/ns1:input = &quot;PROV_DATA&quot;) or ((/ns1:input = &quot;ORDER_DATA&quot;) or ((/ns1:input = &quot;LIFECYCLE_DATA&quot;) or(/ns1:input = &quot;ALL&quot;))))))))))))))">
              <ns1:ErrorTechMessage>
                <xsl:text disable-output-escaping="no">Entry [ input ] has Invalid Value, Valid Values are [ QUERIES_DATA|COMPOSITE_DATA|ERROR_DATA|PARAMETER_DATA|VALIDATION_DATA|MAPPING_DATA|ATTRIBUTEVALIDATION_DATA|SIEBELPRODUCT_DATA|PROFILEATTRIBUTES_DATA|ORDER_DATA|PROV_DATA|LIFECYCLE_DATA|ALL ].</xsl:text>
              </ns1:ErrorTechMessage>
               <ns1:ErrorBusCode>
                <xsl:text disable-output-escaping="no">VF0001</xsl:text>
              </ns1:ErrorBusCode>
              <ns1:ErrorBusMessage>
                <xsl:text disable-output-escaping="no">Validation Fault : Unable to FulFill Transaction, Entry [ input ] has Invalid Value, Valid Values are [ QUERIES_DATA|COMPOSITE_DATA|ERROR_DATA|PARAMETER_DATA|VALIDATION_DATA|MAPPING_DATA|ATTRIBUTEVALIDATION_DATA|SIEBELPRODUCT_DATA|PROFILEATTRIBUTES_DATA|ORDER_DATA|PROV_DATA|LIFECYCLE_DATA|ALL ].</xsl:text>
              </ns1:ErrorBusMessage>
              <ns1:ErrorTechCode>
                <xsl:text disable-output-escaping="no">OFM-VAL-0001</xsl:text>
              </ns1:ErrorTechCode>
            </xsl:when>
          </xsl:choose>
        </ns1:ErrorInformation>
      </ns1:MessageBody>
    </ns1:output>
  </xsl:template>
</xsl:stylesheet>