<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeFinancialInfoReference" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://employee.fact" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HR/EmployeeService/getEmployeeFinancialInfoReference"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ax211="http://employeeFinancial.bean.fact/xsd"
                xmlns:ax230="http://WorkFlowStructure.bean.fact/xsd"
                xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:ns2="http://org.apache.axis2/xsd"
                xmlns:ax28="http://evaluation.bean.fact/xsd" xmlns:ax214="http://employeeInfoDetails.bean.fact/xsd"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ax227="http://salarySlip.bean.fact/xsd"
                xmlns:ax217="http://leave.bean.fact/xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ax224="http://employment.bean.fact/xsd"
                xmlns:ax238="http://dao.fact/xsd" xmlns:ax233="http://utility.bean.fact/xsd"
                xmlns:ax225="http://common.bean.fact/xsd" xmlns:ax221="http://employee.bean.fact/xsd"
                xmlns:ax21="http://vacation.bean.fact/xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ax236="http://email.bean.fact/xsd" xmlns:ax25="http://overTime.bean.fact/xsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/getEmployeeFinancialInfoReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeFinancialInfoReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EmployeeService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getEmployeeFinancialInfoResponse" namespace="http://employee.fact"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED DEC 27 15:31:35 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:getEmployeeFinancialInfoResponse>
         <tns:return>
            <xsl:if test="/ns0:OutputParameters/ns0:P_EMP_ID">
               <ax225:webServiceResponseMessage>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:P_EMP_ID"/>
               </ax225:webServiceResponseMessage>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:AMOUNT">
               <ax211:amount>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:AMOUNT"/>
               </ax211:amount>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:BANK_BRANCH_NO">
               <ax211:bankBranchNumber>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:BANK_BRANCH_NO"/>
               </ax211:bankBranchNumber>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_ACC_NO">
               <ax211:empAccountNumber>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_ACC_NO"/>
               </ax211:empAccountNumber>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_BAS_SAL_CUR">
               <ax211:empBasicSalary>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_BAS_SAL_CUR"/>
               </ax211:empBasicSalary>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_TAX_FLG">
               <ax211:empTaxFlag>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_TAX_FLG"/>
               </ax211:empTaxFlag>
            </xsl:if>
            <xsl:for-each select="/ns0:OutputParameters/ns0:OUT_CUR_BONUSES_INFO/ns0:OUT_CUR_BONUSES_INFO_Row">
               <ax211:employeeBonusesInfos>
                  <xsl:if test="ns0:ALW_CODE">
                     <ax211:bonusDescription>
                        <xsl:value-of select="ns0:ALW_CODE"/>
                     </ax211:bonusDescription>
                  </xsl:if>
                  <xsl:if test="ns0:ALW_VALUE">
                     <ax211:bonusValue>
                        <xsl:value-of select="ns0:ALW_VALUE"/>
                     </ax211:bonusValue>
                  </xsl:if>
               </ax211:employeeBonusesInfos>
            </xsl:for-each>
            <xsl:for-each select="/ns0:OutputParameters/ns0:OUT_CUR_DEDUCTIONS_INFO/ns0:OUT_CUR_DEDUCTIONS_INFO_Row">
               <ax211:employeeDeductionsInfos>
                  <xsl:if test="ns0:ALW_CODE">
                     <ax211:deductionDescription>
                        <xsl:value-of select="ns0:ALW_CODE"/>
                     </ax211:deductionDescription>
                  </xsl:if>
                  <xsl:if test="ns0:ALW_VALUE">
                     <ax211:deductionValue>
                        <xsl:value-of select="ns0:ALW_VALUE"/>
                     </ax211:deductionValue>
                  </xsl:if>
               </ax211:employeeDeductionsInfos>
            </xsl:for-each>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_DAMAN">
               <ax211:familyHelpFlag>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:EMP_DAMAN"/>
               </ax211:familyHelpFlag>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:STY_FALG">
               <ax211:socialSecurityFlag>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:STY_FALG"/>
               </ax211:socialSecurityFlag>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:WORK_WIFE_FLAG">
               <ax211:wifeWorkFlag>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:OUT_CUR_FINANCIAL_INFO/ns0:OUT_CUR_FINANCIAL_INFO_Row/ns0:WORK_WIFE_FLAG"/>
               </ax211:wifeWorkFlag>
            </xsl:if>
         </tns:return>
      </tns:getEmployeeFinancialInfoResponse>
   </xsl:template>
</xsl:stylesheet>
