<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.fact.com/ws/ACI" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CBSReference" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/CARD_MANAGEMENT/AllCardsInquiry/AllCardsInquiry">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/AllCardsInquiryService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CBSReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/AllCardsInquiryService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="AllCardsInquiryMessageOutput" namespace="http://xmlns.fact.com/ws/ACI"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED SEP 06 09:34:54 IDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AllCardsInquiryMessageOutput>
         <tns:MessageHeader>
            <tns:TransactionID/>
         </tns:MessageHeader>
         <tns:MessageBody>
            <tns:InquiryInformation>
               <xsl:for-each select="/ns0:OutputParameters/ns0:IO_CURSOR/ns0:IO_CURSOR_Row">
                  <tns:Card>
                     <tns:CardID>
                        <xsl:value-of select="ns0:CARD_ID"/>
                     </tns:CardID>
                     <tns:CardHolderName>
                        <xsl:value-of select="ns0:CARD_B_FULL_NAME"/>
                     </tns:CardHolderName>
                     <tns:CardHolderNationalNum>
                        <xsl:value-of select="ns0:CARD_NATIONAL_NO"/>
                     </tns:CardHolderNationalNum>
                  </tns:Card>
               </xsl:for-each>
            </tns:InquiryInformation>
         </tns:MessageBody>
      </tns:AllCardsInquiryMessageOutput>
   </xsl:template>
</xsl:stylesheet>
