<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://services.fact"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns="http://services.fact"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="MusawamehService">
        <plnk:role name="MusawamehServicePortType" portType="ns:MusawamehServicePortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://services.fact" location="MusawamehService.wsdl"/>
</wsdl:definitions>
