<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="HCMDepartmentsProcess"
     targetNamespace="http://xmlns.oracle.com/HCMCloudServices/HCMDepartments/HCMDepartmentsProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/HCMCloudServices/HCMDepartments/HCMDepartmentsProcess"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://www.fact.com.jo/ST"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://FACT-MALHAJ.fact.com.jo:7101/soa-infra/services/default/HCMDepartments!2.5/WSDLs/HCMDepartmentsProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="HCMDepartmentsProcess">
        <plnk:role name="HCMDepartmentsProcessProvider" portType="client:HCMDepartmentsProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/HCMCloudServices/HCMDepartments/HCMDepartmentsProcess"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://www.fact.com.jo/ST">
            <import namespace="http://xmlns.oracle.com/HCMCloudServices/HCMDepartments/HCMDepartmentsProcess"
                 schemaLocation="../Schemas/HCMDepartmentsProcess.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.fact.com.jo/ST" schemaLocation="../Schemas/status.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="HCMDepartmentsProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="HCMDepartmentsProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="HCMDepartmentsProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:HCMDepartmentsProcessRequestMessage"/>
            <wsdl:output message="client:HCMDepartmentsProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="HCMDepartmentsProcessBinding" type="client:HCMDepartmentsProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="hcmdepartmentsprocess_service_ep">
        <wsdl:port name="HCMDepartmentsProcess_pt" binding="client:HCMDepartmentsProcessBinding">
            <soap:address location="http://FACT-MALHAJ.fact.com.jo:7101/soa-infra/services/default/HCMDepartments/hcmdepartmentsprocess_service_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
