<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://services.fact" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/saveLoanRequestReference" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ns1="http://org.apache.axis2/xsd"
                xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ax27="http://General.bean.fact/xsd" xmlns:ax25="http://customer.bean.fact/xsd"
                xmlns:ax26="http://common.bean.fact/xsd" xmlns:ax29="http://loan.bean.fact/xsd"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/MUSAWAMEH/MusawamehService/saveLoanRequestReference"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/MusawamehService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="saveLoanRequest" namespace="http://services.fact"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/saveLoanRequestReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/saveLoanRequestReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON FEB 19 08:34:14 IST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:lngCustomerId">
            <tns:P_CUST_ID>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:lngCustomerId"/>
            </tns:P_CUST_ID>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strCustomerName">
            <tns:P_CUST_NAME>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strCustomerName"/>
            </tns:P_CUST_NAME>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intGenderCode">
            <tns:P_PHPR_SEX>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intGenderCode"/>
            </tns:P_PHPR_SEX>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strBirthDate">
            <tns:P_PHPR_BIRTH_DATE>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strBirthDate"/>
            </tns:P_PHPR_BIRTH_DATE>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strNationalNumber">
            <tns:P_PHPR_NATIONAL_NBR>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strNationalNumber"/>
            </tns:P_PHPR_NATIONAL_NBR>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intDocumentCode">
            <tns:P_DCNT_CODE>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intDocumentCode"/>
            </tns:P_DCNT_CODE>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strDocumentNumber">
            <tns:P_PHPR_ID_DOC_NUM>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strDocumentNumber"/>
            </tns:P_PHPR_ID_DOC_NUM>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strAccountNumber">
            <tns:P_CACC_NUM>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strAccountNumber"/>
            </tns:P_CACC_NUM>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intBranchCode">
            <tns:P_BRCH_CODE>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intBranchCode"/>
            </tns:P_BRCH_CODE>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:lngReferenceNumber">
            <tns:P_COND_SEQUENCE>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:lngReferenceNumber"/>
            </tns:P_COND_SEQUENCE>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intCurrencyCode">
            <tns:P_CURR_CODE>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intCurrencyCode"/>
            </tns:P_CURR_CODE>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblGoodAmount">
            <tns:P_RCPM_GOODS_AMNT>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblGoodAmount"/>
            </tns:P_RCPM_GOODS_AMNT>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblDownPayment">
            <tns:P_RCPM_DOWN_PYMNT>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblDownPayment"/>
            </tns:P_RCPM_DOWN_PYMNT>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblFirstBatchRatio">
            <tns:P_RCPM_DOWN_PYMNT_PRCNT>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblFirstBatchRatio"/>
            </tns:P_RCPM_DOWN_PYMNT_PRCNT>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblGracePeriod">
            <tns:P_ILOP_GRACE_PERIOD>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblGracePeriod"/>
            </tns:P_ILOP_GRACE_PERIOD>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intNumberOfInstallments">
            <tns:P_NO_MONTHS>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:intNumberOfInstallments"/>
            </tns:P_NO_MONTHS>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblTotalValueOfFinancing">
            <tns:P_TOT_AMNT>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblTotalValueOfFinancing"/>
            </tns:P_TOT_AMNT>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblValueOfTheMonthlyInstallment">
            <tns:P_MONTH_AMNT>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:dblValueOfTheMonthlyInstallment"/>
            </tns:P_MONTH_AMNT>
         </xsl:if>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strWebUserId">
            <tns:P_WEB_USER_ID>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strWebUserId"/>
            </tns:P_WEB_USER_ID>
         </xsl:if>
         <tns:I_GOOD_CODE>
            <xsl:for-each select="/ns0:saveLoanRequest/ns0:goodsInfo">
               <xsl:if test="ax29:intGoodCode">
                  <tns:I_GOOD_CODE_ITEM>
                     <xsl:value-of select="ax29:intGoodCode"/>
                  </tns:I_GOOD_CODE_ITEM>
               </xsl:if>
            </xsl:for-each>
         </tns:I_GOOD_CODE>
         <tns:I_GOOD_AMNT>
            <xsl:for-each select="/ns0:saveLoanRequest/ns0:goodsInfo">
               <xsl:if test="ax29:dblGoodAmount">
                  <tns:I_GOOD_AMNT_ITEM>
                     <xsl:value-of select="ax29:dblGoodAmount"/>
                  </tns:I_GOOD_AMNT_ITEM>
               </xsl:if>
            </xsl:for-each>
         </tns:I_GOOD_AMNT>
         <xsl:if test="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strDateStamp">
            <tns:P_TIME_STAMP>
               <xsl:value-of select="/ns0:saveLoanRequest/ns0:objLoanRequestInfo/ax29:strDateStamp"/>
            </tns:P_TIME_STAMP>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
