<wsdl:definitions
     name="InsertGradesDDbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMGrades/InsertGradesDDbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HCMCloudServices/HCMGrades/InsertGradesDDbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertGradesDDbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertGradesDDbReference_plt" >
    <plt:role name="InsertGradesDDbReference_role" >
      <plt:portType name="tns:InsertGradesDDbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertGradesDDbReference" schemaLocation="../Schemas/InsertGradesDDbReference_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="HcmGradeDCollection_msg">
        <wsdl:part name="HcmGradeDCollection" element="top:HcmGradeDCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertGradesDDbReference_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:HcmGradeDCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
