<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.fact.com/ws/TI" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionInquiryReference" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/TRANSACTION_MANAGEMENT/TransactionInquiry/TransactionInquiryReference"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/TRANSACTION_MANAGEMENT/TransactionInquiry/TransactionInquiry">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/TransactionInquiryReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionInquiryReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/TransactionInquiryService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="TransactionsInquiryMessageOutput" namespace="http://xmlns.fact.com/ws/TI"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED SEP 06 16:31:07 IDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:TransactionsInquiryMessageOutput>
         <tns:MessageBody>
            <tns:InquiryInformation>
               <xsl:for-each select="/ns0:OutputParameters/ns0:IO_CURSOR/ns0:IO_CURSOR_Row">
                  <tns:Transaction>
                     <tns:TransactionID>
                        <xsl:value-of select="ns0:TRANS_ID"/>
                     </tns:TransactionID>
                     <tns:Date>
                        <xsl:value-of select="ns0:TRANS_DATE"/>
                     </tns:Date>
                     <tns:TransactionTypeID>
                        <xsl:value-of select="ns0:SERIAL_ID"/>
                     </tns:TransactionTypeID>
                     <tns:TransactionTypeName>
                        <xsl:value-of select="ns0:TRANS_B_DESC"/>
                     </tns:TransactionTypeName>
                     <tns:DebitCreditIndicator>
                        <xsl:value-of select="ns0:DRCRNN_SIGN"/>
                     </tns:DebitCreditIndicator>
                     <tns:DebitValue>
                        <xsl:value-of select="ns0:DEBITVALUE"/>
                     </tns:DebitValue>
                     <tns:CreditValue>
                        <xsl:value-of select="ns0:CREDITVALUE"/>
                     </tns:CreditValue>
                     <tns:CardHolderName>
                        <xsl:value-of select="ns0:CARD_B_FULL_NAME"/>
                     </tns:CardHolderName>
                     <tns:Balance> </tns:Balance>
                     <tns:CardHolderNationalNum>
                        <xsl:value-of select="ns0:CARD_NATIONAL_NO"/>
                     </tns:CardHolderNationalNum>
                     <tns:CardID>
                        <xsl:value-of select="ns0:CARD_ID"/>
                     </tns:CardID>
                  </tns:Transaction>
               </xsl:for-each>
            </tns:InquiryInformation>
         </tns:MessageBody>
      </tns:TransactionsInquiryMessageOutput>
   </xsl:template>
</xsl:stylesheet>
