<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SOAPBounsSysEndpoint"
     targetNamespace="http://xmlns.oracle.com/bouns-soa-application/SOABounsSystem/SOAPBounsSysEndpoint"
     xmlns:tns="http://xmlns.oracle.com/bouns-soa-application/SOABounsSystem/SOAPBounsSysEndpoint"
     xmlns:inp1="http://www.example.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/BPELProcessCoreBouns.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="MessageRequest" element="inp1:EmpBonusEmailNotificationMessageRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="MessageResponse" element="inp1:EmpBonusEmailNotificationMessageResponse"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
