<wsdl:definitions
     name="deleteProfitDbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CRE/GetProfitInfo/deleteProfitDbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CRE/GetProfitInfo/deleteProfitDbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/deleteProfitDbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="deleteProfitDbReference_plt" >
    <plt:role name="deleteProfitDbReference_role" >
      <plt:portType name="tns:deleteProfitDbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/deleteProfitDbReference"
               schemaLocation="../Schemas/deleteProfitDbReference_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="deleteProfitDbReference_ptt">
        <wsdl:operation name="deleteProfitDbReference">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
