<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://www.fact.com.jo" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReference" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/SalaryBulk/FileSearch/dbReference"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/SalaryBulk/FileSearch/FileSearch">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/dbReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FileSearch.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Output" namespace="http://www.fact.com.jo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [SAT MAR 24 13:48:11 EET 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Output>
         <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORD/ns0:P_RECORD_Row">
            <tns:GetData>
               <tns:SEQUENCE_NO>
                  <xsl:value-of select="ns0:SEQUENCE_NO"/>
               </tns:SEQUENCE_NO>
               <tns:FILE_CODE>
                  <xsl:value-of select="ns0:FILE_CODE"/>
               </tns:FILE_CODE>
               <tns:FILE_NAME>
                  <xsl:value-of select="ns0:FILE_NAME"/>
               </tns:FILE_NAME>
               <tns:STATUS>
                  <xsl:value-of select="ns0:STATUS"/>
               </tns:STATUS>
               <tns:DATE_OF_PAYMENT>
                  <xsl:value-of select="ns0:DATE_OF_PAYMENT"/>
               </tns:DATE_OF_PAYMENT>
               <tns:NO_OF_SALARIES>
                  <xsl:value-of select="ns0:NO_OF_SALARIES"/>
               </tns:NO_OF_SALARIES>
               <tns:SALARY_AMOUNT>
                  <xsl:value-of select="ns0:SALARY_AMOUNT"/>
               </tns:SALARY_AMOUNT>
               <tns:UPLOAD_DATE>
                  <xsl:value-of select="ns0:UPLOAD_DATE"/>
               </tns:UPLOAD_DATE>
               <tns:UPLOAD_TIME>
                  <xsl:value-of select="ns0:UPLOAD_TIME"/>
               </tns:UPLOAD_TIME>
               <tns:LAST_MODIFICATION_DATE>
                  <xsl:value-of select="ns0:LAST_MODIFICATION_DATE"/>
               </tns:LAST_MODIFICATION_DATE>
               <tns:LAST_MODIFICATION_TIME>
                  <xsl:value-of select="ns0:LAST_MODIFICATION_TIME"/>
               </tns:LAST_MODIFICATION_TIME>
               <tns:PERVIOUS_SEQ>
                  <xsl:value-of select="ns0:PERVIOUS_SEQ"/>
               </tns:PERVIOUS_SEQ>
               <tns:COMPANY_ID>
                  <xsl:value-of select="ns0:COMPANY_ID"/>
               </tns:COMPANY_ID>
               <tns:UPLOADER_ID>
                  <xsl:value-of select="ns0:UPLOADER_ID"/>
               </tns:UPLOADER_ID>
               <tns:COVER_FILE_NAME>
                  <xsl:value-of select="ns0:COVER_FILE_NAME"/>
               </tns:COVER_FILE_NAME>
               <tns:SALARY_FILE_TYPE>
                  <xsl:value-of select="ns0:SALARY_FILE_TYPE"/>
               </tns:SALARY_FILE_TYPE>
               <tns:BRCH_CODE>
                  <xsl:value-of select="ns0:BRCH_CODE"/>
               </tns:BRCH_CODE>
               <tns:CACC_NUM>
                  <xsl:value-of select="ns0:CACC_NUM"/>
               </tns:CACC_NUM>
               <tns:FILE_SOURCE>
                  <xsl:value-of select="ns0:FILE_SOURCE"/>
               </tns:FILE_SOURCE>
               <tns:MONTH_NUM>
                  <xsl:value-of select="ns0:MONTH_NUM"/>
               </tns:MONTH_NUM>
               <tns:CMPN_B_DESC>
                  <xsl:value-of select="ns0:CMPN_B_DESC"/>
               </tns:CMPN_B_DESC>
            </tns:GetData>
         </xsl:for-each>
      </tns:Output>
   </xsl:template>
</xsl:stylesheet>
