<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://xmlns.fact.com/ws/PCBT" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CBSReference" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/TRANSACTION_MANAGEMENT/PrintChequeBooksTransaction/CBSReference"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/TRANSACTION_MANAGEMENT/PrintChequeBooksTransaction/PrintChequeBooksTransactionBPEL">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CBSReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CBSReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/PrintChequeBooksTransactionBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PrintChequeBooksTransactionOutput" namespace="http://xmlns.fact.com/ws/PCBT"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE OCT 03 10:23:12 IDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:PrintChequeBooksTransactionOutput>
         <tns:MessageBody>
            <tns:TransactionInformation>
               <tns:ResponseCode>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:P_RESPCODE"/>
               </tns:ResponseCode>
               <xsl:for-each select="/ns0:OutputParameters/ns0:P_REQUESTS">
                  <tns:Cheque>
                     <tns:BankCode>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:BANK_CODE"/>
                     </tns:BankCode>
                     <tns:CBK_BRCH>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CBK_BRCH"/>
                     </tns:CBK_BRCH>
                     <tns:CACC_NUM>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CACC_NUM"/>
                     </tns:CACC_NUM>
                     <tns:CACC_CD_NUM>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CACC_CD_NUM"/>
                     </tns:CACC_CD_NUM>
                     <tns:CheckBookSerial>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CHECK_BOOK_SERIAL"/>
                     </tns:CheckBookSerial>
                     <tns:FirstNumber>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:FIRST_NB"/>
                     </tns:FirstNumber>
                     <tns:LastNumber>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:LAST_NB"/>
                     </tns:LastNumber>
                     <tns:CheckNumber>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CHK_NUM"/>
                     </tns:CheckNumber>
                     <tns:CBPT_CODE>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CBTP_CODE"/>
                     </tns:CBPT_CODE>
                     <tns:CustomerTitle>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:CUST_TITEL"/>
                     </tns:CustomerTitle>
                     <tns:PrintCustomerName1>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:PRNT_CUST_NAME1"/>
                     </tns:PrintCustomerName1>
                     <tns:PrintCustomerName2>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:PRNT_CUST_NAME2"/>
                     </tns:PrintCustomerName2>
                     <tns:BEN_NAME>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:BEN_NAME"/>
                     </tns:BEN_NAME>
                     <tns:Amount>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:AMOUNT"/>
                     </tns:Amount>
                     <tns:Fraction>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:FRACTION"/>
                     </tns:Fraction>
                     <tns:V_TAFQET>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:V_TAFQET"/>
                     </tns:V_TAFQET>
                     <tns:TodayDate>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:TODAY_DATE"/>
                     </tns:TodayDate>
                     <tns:COMP>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:COMP"/>
                     </tns:COMP>
                     <tns:Note>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:NOTE"/>
                     </tns:Note>
                     <tns:HoldNumber>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:HOLD_NUM"/>
                     </tns:HoldNumber>
                     <tns:NO_OF_HLD>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:NO_OF_HLD"/>
                     </tns:NO_OF_HLD>
                     <tns:Address1>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:ADDRESS1"/>
                     </tns:Address1>
                     <tns:Address2>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:ADDRESS2"/>
                     </tns:Address2>
                     <tns:Address3>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:ADDRESS3"/>
                     </tns:Address3>
                     <tns:EndTitle>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:END_TITLE"/>
                     </tns:EndTitle>
                     <tns:Note2>
                        <xsl:value-of select="ns0:P_REQUESTS_Row/ns0:NOTE2"/>
                     </tns:Note2>
                  </tns:Cheque>
               </xsl:for-each>
            </tns:TransactionInformation>
         </tns:MessageBody>
      </tns:PrintChequeBooksTransactionOutput>
   </xsl:template>
</xsl:stylesheet>
